Added drawer component and conditional rendering to header component
TechOptimum/techoptimum.org pull request #31
Opened 2023-03-27 18:41 UTC by siddharthd0

2023-03-27 19:13 UTC, PranTanTheMan requested changes
The hamburger icon is not to the right and aligned with the logo, the drawer component's background is white and I wonder if we can change the submenu effect for the intiatives and the about links. Otherwise let's address the styling first and then the submenu.

2023-04-03 20:05 UTC, PranTanTheMan approved these changes

2023-04-03 20:06 UTC, PranTanTheMan approved these changes

2023-04-03 20:12 UTC, merged

2023-04-03 20:23 UTC, siddharthd0 commented
@PranTanTheMan Can you clean up the drawer a little to make it look better